config/routes.rb
Rails.application.routes.draw do

  resources :items, only: [:index, :new, :create] do
    resources :traits, only: [:index, :create]
    resources :instances, only: [:index, :new, :create]
  end

  root to: 'items#index'
end

app/models/concrete.rb
class Concrete
  include Neo4j::ActiveRel

  from_class Item
  to_class Instance
  type 'concrete'
end

app/models/dimension.rb
class Dimension
  include Neo4j::ActiveRel

  from_class :any
  to_class :any
  type 'dimension'

  property :name, type: String
end

app/models/facet.rb
class Facet
  include Neo4j::ActiveRel

  from_class Instance
  to_class Trait
  type 'facet'
end

app/models/instance.rb
class Instance
  include Neo4j::ActiveNode

  id_property :id, auto: :uuid

  property :quantity, type: Integer, default: 0

  has_many :out, :traits, rel_class: Facet
  has_one :both, :item, rel_class: Concrete
end

app/models/item.rb
class Item
  include Neo4j::ActiveNode

  property :description
  id_property :id, auto: :uuid

  validates :description, presence: true

  has_many :both, :traits, rel_class: Dimension
  has_many :both, :instances, rel_class: Concrete
end

app/models/trait.rb
class Trait
  include Neo4j::ActiveNode

  property :description
  id_property :id, auto: :uuid

  has_many :both, :items, rel_class: Dimension
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dimensions_controller.rb
class DimensionsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController

  def index
    @item = Item.find(params[:item_id])
    @instances = @item.instances.to_a
  end

  def new
    @item = Item.find(params[:item_id])
    @traits = @item.traits.each_with_rel.reduce(Hash.new { |h,k| h[k] = [] }) do |agg, (node, rel)|
      agg[rel.name] << node
      agg
    end
    @instance = Instance.new
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.to_a
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(params[:item])
    if @item.save
      flash[:success] = t('items.create')
      redirect_to items_path
    else
      flash[:warning] = @item.errors.full_messages
      render :new
    end
  end
end

app/controllers/traits_controller.rb
class TraitsController < ApplicationController

  def index
    @item = Item.where(id: params[:item_id]).first
    @traits = @item.traits.each_with_rel.reduce(Hash.new { |h,k| h[k] = [] }) do |agg, (node, rel)|
      agg[rel.name] << node
      agg
    end
  end

  def create
    @item = Item.where(id: params[:item_id]).first
    trait = Trait.create(description: params[:description])
    dimension = Dimension.create(name: params[:dimension_name], from_node: @item, to_node: trait)
    redirect_to item_traits_path(@item)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dimensions_helper.rb
module DimensionsHelper
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/traits_helper.rb
module TraitsHelper
end

app/views/instances/index.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='col-md-8' %>
      <div class="page-header">
        <h1><%= @item.description.pluralize %> <small><%= @instances.sum(&:quantity) %></small></h1>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-8' %>
      <ul class="list-group">
        <% @instances.each do |inst| %>
          <li class="list-group-item">
            <span class='badge'><%= inst.quantity %></span>
            <%= inst.traits.collect { |f| f.description }.join " " %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-4'>
      <%= link_to 'New Instance', new_item_instance_path(@item), class: 'btn btn-primary', role: 'button' %>
    </div>
  </div>
</div>

app/views/instances/new.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='col-md-8'%>
      <div class="page-header">
        <h1>New instance of <%= @item.description.downcase %></h1>
      </div>
    </div>
  </div>

  <% if flash.present? %>
    <div class='row'>
      <div class='col-md-4'%>
        <%= render partial: 'layouts/alerts' %>
      </div>
    </div>
  <% end %>

  <div class='row'>
    <div class='col-md-4'%>
      <%= form_for [@item, @instance] do |f| %>
        <div class="form-group">
          <%= f.label :quantity %>
          <%= f.text_field :quantity, class: 'form-control', placeholder: 'Item quantity' %>
        </div>
        <div class='form-group'>
          
        </div>
        <%= f.submit 'Create', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', items_path, class: 'btn btn-default', role: 'button' %>
      <% end %>
    </div>
  </div>

app/views/items/index.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class="page-header">
      <h1>Items <small><%= @items.size %></small></h1>
    </div>
  </div>

  <div class='row'>
    <div class='md-col-8' %>
      <table class='table table-hover'>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.description %></td>
              <td><%= link_to 'Traits', item_traits_path(item) %></td>
              <td><%= link_to 'Instances', item_instances_path(item) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class='row'>
    <div class='md-col-4'>
      <%= link_to 'New Item', new_item_path, class: 'btn btn-primary', role: 'button' %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="page-header">
      <h1>New item</h1>
    </div>
  </div>

  <% if flash.present? %>
    <div class='row'>
      <%= render partial: 'layouts/alerts' %>
    </div>
  <% end %>

  <div class='row'>
    <div class='col-md-4'%>
      <%= form_for @item do |f| %>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, class: 'form-control', placeholder: 'Item description' %>
        </div>
        <%= f.submit 'Create', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', items_path, class: 'btn btn-default', role: 'button' %>
      <% end %>
    </div>
  </div>

app/views/layouts/_alerts.html.erb
<div class='container'>
  <% if flash[:warning].present? %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <ul>
        <% flash[:warning].each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if flash[:success].present? %>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <ul>
        <% Array(flash[:success]).each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Itams</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class='container-fluid'>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to 'Nearly', root_path, class: 'navbar-brand' %>
          </div>
          <ul class="nav navbar-nav">
            <li><%= link_to 'Items', items_path %></li>
        </div>
      </nav>

      <%= yield %>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/traits/index.html.erb
<div class='container'>
  <div class='row'>
    <div class="page-header">
      <h1><%= @item.description %></h1>
    </div>
  </div>

  <% if flash.present? %>
    <div class='row'>
      <%= render partial: 'layouts/alerts' %>
    </div>
  <% end %>

  <% @traits.each do |dimension, traits| %>
    <div class='row'>
      <h2><%= dimension %> <small><%= traits.size %></small></h2>
      <ul class="list-group">
        <% traits.each do |trait| %>
          <li class='list-group-item'><%= trait.description %></li>
        <% end %>
      </ul>
    </div>
    <div class='row'>
      <div class='col-md-4'%>
        <%= form_for item_traits_path(@item) do |f| %>
          <%= f.hidden_field dimension %>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_field :description, class: 'form-control', placeholder: 'Trait description' %>
          </div>
          <%= f.submit 'Create', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>